#!/usr/bin/env python3
"""
Generate version_info.txt for PyInstaller from JM_MusicAnalizer/__init__.py
Reads APP_VERSION single source of truth.
"""
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
INIT_FILE = os.path.join(PROJECT_DIR, "JM_MusicAnalizer", "__init__.py")
OUTPUT_FILE = os.path.join(PROJECT_DIR, "version_info.txt")


def read_version() -> str:
    with open(INIT_FILE, encoding="utf-8") as f:
        content = f.read()
    m = re.search(r'APP_VERSION\s*=\s*"([^"]+)"', content)
    if not m:
        print(f"ERROR: APP_VERSION not found in {INIT_FILE}", file=sys.stderr)
        sys.exit(1)
    return m.group(1)


def version_to_tuple(v: str) -> tuple:
    parts = v.split(".")
    parts = [p for p in parts if p.isdigit()]
    while len(parts) < 4:
        parts.append("0")
    return tuple(int(p) for p in parts[:4])


def generate(v: str) -> str:
    vt = version_to_tuple(v)
    return f"""# Autogenerated by generate_version_info.py from JM_MusicAnalizer/__init__.py
# Do not edit manually.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vt},
    prodvers={vt},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [StringStruct(u'CompanyName', u'JM Music'),
           StringStruct(u'FileDescription', u'JM Music Analyzer'),
           StringStruct(u'FileVersion', u'{v}'),
           StringStruct(u'InternalName', u'JM-MusicAnalyzer'),
           StringStruct(u'LegalCopyright', u'JM Music'),
           StringStruct(u'OriginalFilename', u'JM-MusicAnalyzer.exe'),
           StringStruct(u'ProductName', u'JM Music Analyzer'),
           StringStruct(u'ProductVersion', u'{v}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def main():
    version = read_version()
    content = generate(version)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[OK] version_info.txt generated: {version}")
    print(f"     {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
